FROM node:17-alpine AS builder
WORKDIR /frontend
COPY ./frontend/package.json ./
RUN npm install
ENV NODE_ENV=production
ENV PREDICT="http://predict:8000"
RUN mkdir app 
COPY ./frontend ./
RUN npm run build
CMD ["npm", "run" ,"start"]



