FROM python:3.10-bullseye
RUN apt update -y && apt upgrade -y

RUN python3 -m pip install poetry
WORKDIR /backend 
COPY ./backend/poetry.lock ./backend/pyproject.toml ./
RUN poetry config virtualenvs.in-project true --local
RUN poetry install --no-dev
COPY ./backend .
ENTRYPOINT ["poetry", "run", "uvicorn", "app:app", "--host", "0.0.0.0"]

